global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 15s

  # The labels to add to any time series or alerts when communicating with external systems
  # (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'master'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9145']
